language: generic
sudo: required
before_install:
  - git config --global user.name "$USERNAME" 
  - git config --global user.email "$EMAIL"
before_script:
  - chmod +x auto-update.sh
script:
  - ls
  - bash auto-update.sh
